services:
  backend:
    build:
      context: ./backend_app01/backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
    # Backnend connects to service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/chat
      SPRING_DATASOURCE_USERNAME: bank
      SPRING_DATASOURCE_PASSWORD: bank
      # Must exist before starts
    depends_on:
      mysql_db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend_app01/chat
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
    depends_on:
      backend:
        condition: service_started

  mysql_db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bank
      MYSQL_PASSWORD: bank
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

volumes:
  db_data:
